name: Issue Labeled
env:
  BUN_VERSION: 1.1.13

on:
  issues:
    types: [labeled]

jobs:
  reply-labeled:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'crash'
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts
            .github
            CMakeLists.txt
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
        with:
          bun-version: "1.1.13"
      - name: "add platform and command label"
        id: add-labels
        env:
          GITHUB_ISSUE_BODY: ${{ github.event.issue.body }}
          GITHUB_ISSUE_TITLE: ${{ github.event.issue.title }}
        shell: bash
        run: |
          LABELS=$(bun scripts/read-issue.ts)
          echo "labels=$LABELS" >> $GITHUB_OUTPUT
          bun scripts/is-outdated.ts >> $GITHUB_OUTPUT
      - name: Add labels
        uses: actions-cool/issues-helper@v3
        with:
          actions: "add-labels"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: ${{ steps.add-labels.outputs.labels }}
      - name: Comment outdated
        if: steps.add-labels.outputs.is_outdated == 'true'
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-comment"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            The latest version of Bun is v${{ steps.add-labels.outputs.latest }}, but you are using v${{ steps.add-labels.outputs.oudated }}.

            If you upgrade to the latest version, does this fix the issue?

            ```sh
            bun upgrade
            ```
